[workspace]
members = [ "json_to_memes_extractor", "memetic_code/emoji_llm_machine_rust","source/github/meta-introspector/streamofrandom/livestream-tiktok-plugin/tiktok_cli_adaptor", "source/github/meta-introspector/streamofrandom/livestream-tiktok-plugin/tiktok_viewer_tracker", "tools/if-counter", "memetic_code/log_processor", "pick-up-nix-cli"]


