#!/usr/bin/env bash

set -euo pipefail

# This script runs the command generated by the generate_update_lock_command.sh script.

# Generate the command
CMD=$(bash scripts/generate_update_lock_command.sh)

# Run the command
echo "Running: $CMD"
$CMD
